#!/usr/bin/env bash
set -euo pipefail

# ── Shell-safe variable assignments ──
MEMCLAW_API_URL=http://localhost:8000
MEMCLAW_API_KEY=''
MEMCLAW_FLEET_ID=''
MEMCLAW_TENANT_ID=''
MEMCLAW_NODE_NAME="$(hostname)"
MEMCLAW_VERSION=2.5.0

echo "=== MemClaw Plugin Installer ==="
echo ""

PLUGIN_DIR="$HOME/.openclaw/plugins/memclaw"
CONFIG_PATH="$HOME/.openclaw/openclaw.json"

# When the on-prem uses self-signed TLS, the bootstrap fetches below
# (plugin-source, tools.json, SKILL.md) hit certificate verification
# errors before step 8 has a chance to install the trust anchor.
# Switch to TOFU mode for the bootstrap curls when MEMCLAW_API_URL is
# HTTPS — same reasoning as `docker login` against a self-signed
# registry. After install, NODE_EXTRA_CA_CERTS handles long-term
# trust at runtime, so no -k anywhere outside this script.
case "$MEMCLAW_API_URL" in
  https://*) CURL_INSECURE="-k" ;;
  *)         CURL_INSECURE="" ;;
esac

# 1. Create directory structure
echo "[1/7] Creating plugin directory..."
mkdir -p "$PLUGIN_DIR/src"

# 2. Write package.json
echo "[2/7] Writing package.json..."
cat > "$PLUGIN_DIR/package.json" << PACKAGE_EOF
{
  "name": "@caura/memclaw",
  "version": "$MEMCLAW_VERSION",
  "description": "OpenClaw plugin for MemClaw central memory",
  "private": true,
  "type": "module",
  "main": "dist/index.js",
  "openclaw": {
    "extensions": ["./dist/index.js"]
  },
  "scripts": {
    "build": "tsc",
    "dev": "tsc --watch"
  },
  "devDependencies": {
    "@types/node": "^25.4.0",
    "typescript": "^5.4"
  }
}
PACKAGE_EOF

# 3. Write tsconfig.json
echo "[3/7] Writing tsconfig.json..."
cat > "$PLUGIN_DIR/tsconfig.json" << 'TSCONFIG_EOF'
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "Node16",
    "moduleResolution": "Node16",
    "outDir": "dist",
    "rootDir": "src",
    "strict": true,
    "esModuleInterop": true,
    "declaration": true
  },
  "include": ["src"]
}
TSCONFIG_EOF

# 4. Fetch plugin manifest from the server (single source of truth).
# Previously this was a baked HEREDOC, which caused silent drift
# whenever the canonical ``plugin/openclaw.plugin.json`` gained new
# fields (notably ``contracts.tools``, required by OpenClaw upstream
# from 2026-05-01) — the on-disk file in the repo had the field, but
# the HEREDOC the installer wrote to fresh installs did not, so every
# fresh install silently lost the tool surface. Fetching from
# ``/plugin-source`` keeps the canonical file the only source.
echo "[4/7] Fetching plugin manifest from $MEMCLAW_API_URL..."
curl $CURL_INSECURE -sf "$MEMCLAW_API_URL/api/plugin-source?file=openclaw.plugin.json" > "$PLUGIN_DIR/openclaw.plugin.json" || {
  echo "ERROR: Could not fetch openclaw.plugin.json from $MEMCLAW_API_URL/api/plugin-source?file=openclaw.plugin.json"
  exit 1
}

# 5. Fetch latest plugin source from MemClaw server
echo "[5/7] Fetching latest plugin source from $MEMCLAW_API_URL..."
for srcfile in index.ts prompt-section.ts tools.ts tool-specs.ts version.ts env.ts transport.ts validation.ts config.ts paths.ts logger.ts resolve-agent.ts tool-definitions.ts deploy.ts heartbeat.ts educate.ts context-engine.ts agent-auth.ts health.ts install-id.ts identity.ts reconcile-skills.ts; do
  curl $CURL_INSECURE -sf "$MEMCLAW_API_URL/api/plugin-source?file=$srcfile" > "$PLUGIN_DIR/src/$srcfile" || {
    echo "ERROR: Could not fetch $srcfile from $MEMCLAW_API_URL/api/plugin-source?file=$srcfile"
    exit 1
  }
done
# tools.json sits at plugin root (loaded at runtime by tool-specs.ts)
curl $CURL_INSECURE -sf "$MEMCLAW_API_URL/api/plugin-source?file=tools.json" > "$PLUGIN_DIR/tools.json" || {
  echo "ERROR: Could not fetch tools.json"
  exit 1
}
# Shared plugin skill file — OpenClaw discovers this via openclaw.plugin.json:skills
mkdir -p "$PLUGIN_DIR/skills/memclaw" || {
  echo "ERROR: Could not create skills directory"
  exit 1
}
curl $CURL_INSECURE -sf "$MEMCLAW_API_URL/api/plugin-source?file=skills/memclaw/SKILL.md" > "$PLUGIN_DIR/skills/memclaw/SKILL.md" || {
  echo "ERROR: Could not fetch skills/memclaw/SKILL.md"
  exit 1
}
echo "    Downloaded all plugin source files"

# Generate version.ts (imported by index.ts)
cat > "$PLUGIN_DIR/src/version.ts" << VERSION_EOF
// Auto-generated by install script
export const PLUGIN_VERSION = "$MEMCLAW_VERSION";
VERSION_EOF

# Write .env file (includes heartbeat config)
cat > "$PLUGIN_DIR/.env" << ENV_EOF
MEMCLAW_API_URL=$MEMCLAW_API_URL
MEMCLAW_API_KEY=$MEMCLAW_API_KEY
MEMCLAW_FLEET_ID=$MEMCLAW_FLEET_ID
MEMCLAW_TENANT_ID=$MEMCLAW_TENANT_ID
MEMCLAW_NODE_NAME=$MEMCLAW_NODE_NAME
ENV_EOF
chmod 600 "$PLUGIN_DIR/.env"

# 6. Install dependencies and build
echo "[6/7] Installing dependencies and building..."
cd "$PLUGIN_DIR"
npm install --silent --no-optional --no-fund --no-audit 2>&1 || true
npm run build 2>&1
echo "    Build successful"

# 7. Configure OpenClaw
echo "[7/7] Configuring OpenClaw..."
if [ -f "$CONFIG_PATH" ]; then
  # Write a temp script to safely modify JSON (avoids inline node -e quoting issues)
  _SETUP_JS=$(mktemp /tmp/memclaw-setup-XXXXXX.mjs)
  cat > "$_SETUP_JS" << 'SETUP_EOF'
import fs from 'fs';
const configPath = process.argv[2];
const pluginDir = process.argv[3];
const config = JSON.parse(fs.readFileSync(configPath, 'utf-8'));

if (!config.plugins) config.plugins = {};
if (!Array.isArray(config.plugins.allow)) config.plugins.allow = [];
if (!config.plugins.allow.includes('memclaw')) config.plugins.allow.push('memclaw');

if (!config.plugins.entries) config.plugins.entries = {};
config.plugins.entries.memclaw = { enabled: true, config: {} };

// Disable memory-core — OpenClaw only loads one kind:"memory" plugin at a time.
// Without this, the memory slot stays with memory-core and register() is never called.
if (config.plugins.entries['memory-core']) {
  config.plugins.entries['memory-core'].enabled = false;
}

// Claim the exclusive memory slot
if (!config.plugins.slots) config.plugins.slots = {};
config.plugins.slots.memory = 'memclaw';

if (!config.plugins.load) config.plugins.load = {};
if (!Array.isArray(config.plugins.load.paths)) config.plugins.load.paths = [];
if (!config.plugins.load.paths.includes(pluginDir)) config.plugins.load.paths.push(pluginDir);

if (!config.tools) config.tools = {};
if (!Array.isArray(config.tools.alsoAllow)) config.tools.alsoAllow = [];
const tools = ['memclaw_recall','memclaw_write','memclaw_manage','memclaw_doc','memclaw_list','memclaw_entity_get','memclaw_tune','memclaw_insights','memclaw_evolve','memclaw_stats'];
for (const t of tools) {
  if (!config.tools.alsoAllow.includes(t)) config.tools.alsoAllow.push(t);
}

fs.writeFileSync(configPath, JSON.stringify(config, null, 2) + '\n');
console.log('    Updated openclaw.json');
SETUP_EOF
  node "$_SETUP_JS" "$CONFIG_PATH" "$PLUGIN_DIR" 2>&1
  rm -f "$_SETUP_JS"
else
  echo "    WARNING: $CONFIG_PATH not found — you will need to configure allowlist manually"
fi

# 8. TLS trust bootstrap — only when MEMCLAW_API_URL is HTTPS.
# OSS / dev installs (http://localhost:8000) skip this entirely.
# For an enterprise on-prem with a self-signed cert, the gateway exposes
# the cert at /onprem-ca.pem; we curl it once with -k (TOFU — same trust
# pattern as `docker login` to a self-signed registry), save it next to
# the plugin, and write a systemd drop-in that exports
# NODE_EXTRA_CA_CERTS so Node trusts it across openclaw-gateway restarts.
case "$MEMCLAW_API_URL" in
  https://*)
    echo "[8/8] Bootstrapping TLS trust for $MEMCLAW_API_URL"
    if curl -ksSL "$MEMCLAW_API_URL/onprem-ca.pem" -o "$PLUGIN_DIR/onprem-ca.pem"         && [ -s "$PLUGIN_DIR/onprem-ca.pem" ]         && head -1 "$PLUGIN_DIR/onprem-ca.pem" | grep -q '^-----BEGIN CERTIFICATE-----$'; then
      chmod 0644 "$PLUGIN_DIR/onprem-ca.pem"
      _SD_DIR="$HOME/.config/systemd/user/openclaw-gateway.service.d"
      mkdir -p "$_SD_DIR"
      cat > "$_SD_DIR/memclaw-tls.conf" << SDEOF
[Service]
Environment="NODE_EXTRA_CA_CERTS=$PLUGIN_DIR/onprem-ca.pem"
SDEOF
      # daemon-reload so the next openclaw-gateway start picks up the env.
      # Skip the failure path quietly — some hosts run openclaw differently
      # (Docker-in-Docker, custom init), in which case the customer just
      # needs NODE_EXTRA_CA_CERTS set however their wrapper accepts env.
      systemctl --user daemon-reload 2>/dev/null || true
      # Also export NODE_EXTRA_CA_CERTS for the user's interactive shell so
      # `openclaw agent` invoked from the CLI (which spawns its own embedded
      # plugin process when it can't reach the gateway) trusts the same cert.
      # The systemd drop-in only covers the openclaw-gateway *service*, not
      # the customer's terminal sessions. Idempotent — guarded by a marker
      # comment so re-running install-plugin doesn't append duplicates.
      _RC_MARKER="# memclaw-onprem CA - managed by install-plugin"
      _RC_LINE='[ -r "'"$PLUGIN_DIR"'/onprem-ca.pem" ] && export NODE_EXTRA_CA_CERTS="'"$PLUGIN_DIR"'/onprem-ca.pem"'
      for _RC in "$HOME/.bashrc" "$HOME/.zshrc" "$HOME/.profile"; do
        [ -f "$_RC" ] || continue
        if ! grep -qF "$_RC_MARKER" "$_RC"; then
          printf '
%s
%s
' "$_RC_MARKER" "$_RC_LINE" >> "$_RC"
        fi
      done
      echo "    Saved CA → $PLUGIN_DIR/onprem-ca.pem"
      echo "    Drop-in   → $_SD_DIR/memclaw-tls.conf"
      echo "    Shell env → ~/.bashrc + ~/.zshrc (NODE_EXTRA_CA_CERTS for new shells)"
    else
      rm -f "$PLUGIN_DIR/onprem-ca.pem"
      echo "    WARNING: could not fetch $MEMCLAW_API_URL/onprem-ca.pem."
      echo "    If your on-prem uses a publicly-trusted cert (Let's Encrypt or"
      echo "    a corporate CA already in the system trust store), this is fine."
      echo "    Otherwise plugin requests will fail TLS verification — either"
      echo "    trust the cert manually or set NODE_TLS_REJECT_UNAUTHORIZED=0"
      echo "    in the openclaw-gateway environment (insecure)."
    fi
    ;;
esac

echo ""
echo "=== Installation complete ==="
echo ""
echo "Plugin directory: $PLUGIN_DIR"
echo "API URL:          $MEMCLAW_API_URL"
echo "Fleet ID:         $MEMCLAW_FLEET_ID"
echo "API Key:          (not set)"
echo ""
echo "Next: restart your OpenClaw gateway to activate the plugin."
echo "  Linux:  systemctl --user restart openclaw-gateway"
echo '  macOS:  launchctl kickstart -k "gui/$(id -u)/ai.openclaw.gateway"'
echo ""
echo "After restart, MemClaw will:"
echo "  1. Claim the memory slot (replacing memory-core)"
echo "  2. Load the plugin and register 10 tools"
echo "  3. Auto-educate your agents (SKILL.md, TOOLS.md, AGENTS.md, HEARTBEAT.md)"
echo "  4. Start heartbeating to the MemClaw API"
echo ""
echo "Your node will appear in Fleet Management within 60 seconds."
echo ""
